baseURL = 'https://flickdm.github.io/'
locale = 'en-us'
title = "Doug's Blog"
theme = 'terminal'

[params]
  CenterTheme = true
  ReadMore = "Read More"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    identifier = "about"
    weight = 1
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "posts"
    weight = 2
    name = "Posts"
    url = "/posts/"

  [[menu.main]]
    identifier = "reading"
    weight = 3
    name = "Reading List"
    url = "/reading/"

  [[menu.main]]
    identifier = "dev_setup"
    weight = 4
    name = "Dev Setup"
    url = "/dev_setup/"
